#pragma once
#include <windows.h>

#define GIGA_IOCTL(index, method, access) CTL_CODE(FILE_DEVICE_UNKNOWN, index, method, access)
#define IOCTL_PCIES2MM_WRITE_REG GIGA_IOCTL(0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCIES2MM_READ_REG GIGA_IOCTL(0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCIES2MM_REGISTER_EVENT GIGA_IOCTL(0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCIES2MM_GET_FRAME GIGA_IOCTL(0x803, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_PCIES2MM_UNREGISTER_EVENT GIGA_IOCTL(0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GIGA_VIDEO_START GIGA_IOCTL(0x830, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GIGA_VIDEO_STOP GIGA_IOCTL(0x831, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GIGA_RELEASE_VIDEO_FRAME GIGA_IOCTL(0x832, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GIGA_ACQUIRE_VIDEO_FRAME_ZEROCOPY GIGA_IOCTL(0x833, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GIGA_ENABLE_FRAME_ZEROCOPY GIGA_IOCTL(0x834, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_GIGA_DISABLE_FRAME_ZEROCOPY GIGA_IOCTL(0x835, METHOD_NEITHER, FILE_ANY_ACCESS)

struct GIGA_REG_ACCESS { ULONG Offset; ULONG Value; };
struct GIGA_EVENT_REG { ULONG Type; ULONG ChannelIndex; HANDLE EventHandle; };
