/*
 * PCIES2MM driver public contract used by the GVFG backend.
 */

#pragma once

#include <stdint.h>
#include <windows.h>

#define PCIES2MM_IOCTL(index, method, access) CTL_CODE(FILE_DEVICE_UNKNOWN, index, method, access)

#define IOCTL_PCIES2MM_WRITE_REG PCIES2MM_IOCTL(0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCIES2MM_READ_REG PCIES2MM_IOCTL(0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCIES2MM_REGISTER_EVENT PCIES2MM_IOCTL(0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCIES2MM_GET_FRAME PCIES2MM_IOCTL(0x803, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_PCIES2MM_UNREGISTER_EVENT PCIES2MM_IOCTL(0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCIES2MM_WRITE_REG_BAR1 PCIES2MM_IOCTL(0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCIES2MM_READ_REG_BAR1 PCIES2MM_IOCTL(0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PCIES2MM_GET_VIDEO_DONE_INDEX PCIES2MM_IOCTL(0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)

enum
{
    PCIES2MM_EVENT_TYPE_VIDEO_DMA = 0,
    PCIES2MM_EVENT_TYPE_VIDEO_FORMAT_CHANGE = 1,
    PCIES2MM_EVENT_TYPE_VIDEO_PLUGIN = 2,
    PCIES2MM_EVENT_TYPE_VIDEO_UNPLUG = 3,
    PCIES2MM_EVENT_TYPE_AUDIO_DMA = 4
};

typedef struct PCIES2MM_REG_ACCESS
{
    ULONG Offset;
    ULONG Value;
} PCIES2MM_REG_ACCESS;

typedef struct PCIES2MM_EVENT_REG
{
    ULONG Type;
    ULONG ChannelIndex;
    HANDLE EventHandle;
} PCIES2MM_EVENT_REG;
